use numpy.testing.assert_allclose over assert np.(all|is)close
for much better error messages

AssertionError:
Not equal to tolerance rtol=1e-07, atol=0.05

Mismatched elements: 5 / 5 (100%)
Max absolute difference: 20.93780092
Max relative difference: 0.00351895
 x: array([ 5076.241999,  5402.944837,  6781.803129,  8742.033493,
       10939.957742])
 y: array([ 5058.441588,  5385.880586,  6765.198542,  8723.785881,
       10919.019941])

vs previously

AssertionError: assert False

also remove unused float precision