fix get_zfile()
refactor caused     raise FileNotFoundError(f"Could not find {base_name} or {base_name}.gz file.")
FileNotFoundError: Could not find INCAR or INCAR.gz file.